/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SheetExtendPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  minWidth: 50,
  maxWidth: 500,
  defaultWidth: 150,
  nativeProcessing: true
};
var SheetExtendSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Sheet Extend Settings" });
    new import_obsidian.Setting(containerEl).setName("Minimum column width").setDesc("Minimum width for a resized column (px)").addSlider(
      (slider) => slider.setLimits(30, 100, 5).setValue(this.plugin.settings.minWidth).onChange(async (value) => {
        this.plugin.settings.minWidth = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Maximum column width").setDesc("Maximum width for a resized column (px)").addSlider(
      (slider) => slider.setLimits(200, 800, 10).setValue(this.plugin.settings.maxWidth).onChange(async (value) => {
        this.plugin.settings.maxWidth = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default column width").setDesc("Default column width when resized (px)").addSlider(
      (slider) => slider.setLimits(80, 300, 5).setValue(this.plugin.settings.defaultWidth).onChange(async (value) => {
        this.plugin.settings.defaultWidth = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable native table processing").setDesc("Automatically process all markdown tables (not just sheet code blocks)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.nativeProcessing).onChange(async (value) => {
        this.plugin.settings.nativeProcessing = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/sheet/parser.ts
function parseTable(text) {
  const lines = text.split("\n").map((l) => l.trim()).filter((l) => l.length > 0);
  if (lines.length < 2) {
    return { grid: [], alignments: [] };
  }
  const rawRows = lines.map((line) => {
    const inner = line.startsWith("|") ? line.slice(1) : line;
    const trimmed = inner.endsWith("|") ? inner.slice(0, -1) : inner;
    return trimmed.split("|").map((c) => c.trim());
  });
  let delimIdx = -1;
  for (let i = 1; i < rawRows.length; i++) {
    if (rawRows[i].every((c) => /^:?-{3,}:?$/.test(c))) {
      delimIdx = i;
      break;
    }
  }
  const alignments = [];
  if (delimIdx >= 0) {
    for (const cell of rawRows[delimIdx]) {
      const left = cell.startsWith(":");
      const right = cell.endsWith(":");
      if (left && right)
        alignments.push("center");
      else if (right)
        alignments.push("right");
      else if (left)
        alignments.push("left");
      else
        alignments.push("default");
    }
  }
  const dataRows = delimIdx >= 0 ? rawRows.slice(delimIdx + 1) : rawRows.slice(1);
  const headerRows = delimIdx > 0 ? rawRows.slice(0, delimIdx) : [rawRows[0]];
  const colCount = Math.max(...dataRows.map((r) => r.length), ...headerRows.map((r) => r.length));
  const verticalHeaderCols = Array(colCount).fill(true);
  for (const row of dataRows) {
    for (let c = 0; c < colCount; c++) {
      const cell = (c < row.length ? row[c] : "").replace(/[`*_~]/g, "");
      if (cell !== "" && !/^:?-{3,}:?$/.test(cell)) {
        verticalHeaderCols[c] = false;
      }
    }
  }
  const grid = [];
  for (const row of headerRows) {
    const gridRow = [];
    for (let c = 0; c < colCount; c++) {
      const text2 = c < row.length ? row[c] : "";
      const cell = { text: text2, colspan: 1, rowspan: 1, hidden: false, isHeader: true };
      gridRow.push(cell);
    }
    grid.push(gridRow);
  }
  for (const row of dataRows) {
    const gridRow = [];
    for (let c = 0; c < colCount; c++) {
      const text2 = c < row.length ? row[c] : "";
      const isHeader = verticalHeaderCols[c] || false;
      const cell = { text: text2, colspan: 1, rowspan: 1, hidden: false, isHeader };
      gridRow.push(cell);
    }
    grid.push(gridRow);
  }
  return { grid, alignments };
}
function applyMerges(grid) {
  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < grid[r].length; c++) {
      const cell = grid[r][c];
      if (cell.hidden)
        continue;
      if (cell.text === "<" && c > 0) {
        for (let pc = c - 1; pc >= 0; pc--) {
          const prev = grid[r][pc];
          if (!prev.hidden) {
            prev.colspan = (prev.colspan || 1) + 1;
            cell.hidden = true;
            break;
          }
        }
      } else if (cell.text === "^" && r > 0) {
        for (let pr = r - 1; pr >= 0; pr--) {
          const prev = grid[pr][c];
          if (!prev.hidden) {
            prev.rowspan = (prev.rowspan || 1) + 1;
            cell.hidden = true;
            break;
          }
        }
      }
    }
  }
}
function stripMergeMarkers(grid) {
  for (const row of grid) {
    for (const cell of row) {
      if (!cell.hidden) {
        cell.text = cell.text.replace(/[<^]/g, "").trim();
      }
    }
  }
}
function parseAndMerge(text) {
  const result = parseTable(text);
  applyMerges(result.grid);
  stripMergeMarkers(result.grid);
  return result;
}

// src/sheet/renderer.ts
var import_obsidian2 = require("obsidian");
function renderTable(app, tableEl, parsed, sourcePath, component) {
  const { grid, alignments } = parsed;
  tableEl.empty();
  tableEl.id = "obsidian-sheets-parsed";
  tableEl.removeAttribute("data-resizable");
  if (grid.length === 0)
    return;
  const headerCount = 1;
  const headerRows = grid.slice(0, headerCount);
  const dataRows = grid.slice(headerCount);
  if (headerRows.length > 0) {
    const thead = tableEl.createEl("thead");
    for (const row of headerRows) {
      const tr = thead.createEl("tr");
      for (let c = 0; c < row.length; c++) {
        const cell = row[c];
        if (cell.hidden)
          continue;
        const th = tr.createEl("th");
        if (alignments[c]) {
          th.style.textAlign = alignments[c] === "default" ? "left" : alignments[c];
        }
        if (cell.colspan > 1)
          th.colSpan = cell.colspan;
        if (cell.rowspan > 1)
          th.rowSpan = cell.rowspan;
        th.setAttribute("data-row", "0");
        th.setAttribute("data-col", String(c));
        import_obsidian2.MarkdownRenderer.render(app, cell.text, th, sourcePath, component);
      }
    }
  }
  if (dataRows.length > 0) {
    const tbody = tableEl.createEl("tbody");
    for (let r = 0; r < dataRows.length; r++) {
      const tr = tbody.createEl("tr");
      for (let c = 0; c < dataRows[r].length; c++) {
        const cell = dataRows[r][c];
        if (cell.hidden)
          continue;
        const tag = cell.isHeader ? "th" : "td";
        const td = tr.createEl(tag);
        if (alignments[c]) {
          td.style.textAlign = alignments[c] === "default" ? "left" : alignments[c];
        }
        if (cell.colspan > 1)
          td.colSpan = cell.colspan;
        if (cell.rowspan > 1)
          td.rowSpan = cell.rowspan;
        td.setAttribute("data-row", String(r + 1));
        td.setAttribute("data-col", String(c));
        import_obsidian2.MarkdownRenderer.render(app, cell.text, td, sourcePath, component);
      }
    }
  }
}

// src/resizer/resizer.ts
function makeTableResizable(plugin, tableEl, onWidthsChanged) {
  if (tableEl.hasAttribute("data-resizable"))
    return;
  tableEl.setAttribute("data-resizable", "true");
  const firstRow = tableEl.querySelector("tr");
  if (!firstRow)
    return;
  const colCount = firstRow.children.length;
  const settings = plugin.settings;
  for (const cell of Array.from(tableEl.querySelectorAll("th, td"))) {
    const cellIndex = cell.getAttribute("data-col");
    if (cellIndex && parseInt(cellIndex) >= colCount - 1)
      continue;
    if (!cellIndex && cell.cellIndex >= colCount - 1)
      continue;
    cell.style.position = "relative";
    const handle = document.createElement("div");
    handle.className = "sheet-extend-resizer";
    cell.appendChild(handle);
    let startX = 0;
    let startWidth = 0;
    handle.addEventListener("mousedown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const rows = Array.from(tableEl.querySelectorAll("tr"));
      if (rows.length === 0)
        return;
      const idx = cellIndex ? parseInt(cellIndex) : cell.cellIndex;
      if (idx === 0)
        return;
      const firstCell = rows[0].children[idx];
      startWidth = firstCell.offsetWidth;
      startX = e.clientX;
      tableEl.setAttribute("data-resizing", "true");
      document.body.classList.add("sheet-extend-resizing");
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
    });
    const onMouseMove = (e) => {
      const diff = e.clientX - startX;
      const newWidth = Math.max(
        settings.minWidth,
        Math.min(settings.maxWidth, startWidth + diff)
      );
      const idx = cellIndex ? parseInt(cellIndex) : cell.cellIndex;
      for (const row of Array.from(tableEl.querySelectorAll("tr"))) {
        const target = row.children[idx];
        if (target) {
          target.style.width = newWidth + "px";
          target.style.minWidth = newWidth + "px";
          target.style.maxWidth = newWidth + "px";
        }
      }
    };
    const onMouseUp = () => {
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
      tableEl.removeAttribute("data-resizing");
      document.body.classList.remove("sheet-extend-resizing");
      const widths = [];
      const firstRow2 = tableEl.querySelector("tr");
      if (firstRow2) {
        for (let i = 0; i < firstRow2.children.length; i++) {
          const el = firstRow2.children[i];
          widths.push(el.style.width ? parseInt(el.style.width) : null);
        }
      }
      onWidthsChanged(widths);
    };
  }
}

// src/resizer/persistence.ts
function getTableId(tableEl) {
  const text = tableEl.textContent || "";
  const hash = text.slice(0, 100).replace(/\s+/g, " ").trim();
  return `table-${hash.length}-${hash.slice(0, 50).replace(/[^a-zA-Z0-9]/g, "_")}`;
}
function saveWidths(plugin, tableId, widths) {
  const store = plugin.widthStore || {};
  const hasData = widths.some((w) => w !== null);
  if (hasData) {
    store[tableId] = widths;
  } else {
    delete store[tableId];
  }
  plugin.widthStore = store;
  plugin.saveData({
    settings: plugin.settings,
    columnWidths: store
  });
}
function loadWidths(plugin, tableId) {
  const store = plugin.widthStore || {};
  return store[tableId] || null;
}
function applySavedWidths(tableEl, widths) {
  for (const row of Array.from(tableEl.querySelectorAll("tr"))) {
    for (let i = 0; i < row.children.length && i < widths.length; i++) {
      const w = widths[i];
      if (w !== null) {
        const el = row.children[i];
        el.style.width = w + "px";
        el.style.minWidth = w + "px";
        el.style.maxWidth = w + "px";
      }
    }
  }
}

// main.ts
var SheetExtendPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.widthStore = {};
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SheetExtendSettingTab(this.app, this));
    this.registerMarkdownPostProcessor((element, context) => {
      if (!this.settings.nativeProcessing)
        return;
      if (!this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView))
        return;
      const tables = Array.from(element.querySelectorAll("table:not([id='obsidian-sheets-parsed'])"));
      for (const tableEl of tables) {
        this.processTable(tableEl, context);
      }
    });
    this.registerMarkdownCodeBlockProcessor("sheet", (source, el, ctx) => {
      const parsed = parseAndMerge(source);
      const tableEl = el.createEl("table");
      renderTable(this.app, tableEl, parsed, ctx.sourcePath, this);
      this.setupResizer(tableEl);
    });
  }
  processTable(tableEl, context) {
    var _a;
    const tableId = getTableId(tableEl);
    let sourceText = "";
    if (context.getSectionInfo) {
      const sectionInfo = context.getSectionInfo(tableEl);
      if (sectionInfo) {
        const lines = sectionInfo.text.split("\n");
        sourceText = lines.slice(sectionInfo.lineStart, sectionInfo.lineEnd + 1).join("\n");
      }
    }
    if (!sourceText) {
      const rows = [];
      for (const tr of Array.from(tableEl.querySelectorAll("tr"))) {
        const cells = [];
        for (const td of Array.from(tr.querySelectorAll("th, td"))) {
          cells.push(td.textContent || "");
        }
        rows.push("| " + cells.join(" | ") + " |");
      }
      sourceText = rows.join("\n");
      if (rows.length > 1) {
        const colCount = ((_a = tableEl.querySelector("tr")) == null ? void 0 : _a.children.length) || 1;
        const delim = "| " + Array(colCount).fill("---").join(" | ") + " |";
        sourceText = rows[0] + "\n" + delim + "\n" + rows.slice(1).join("\n");
      }
    }
    const parsed = parseAndMerge(sourceText);
    renderTable(this.app, tableEl, parsed, context.sourcePath || "", this);
    const savedWidths = loadWidths(this, tableId);
    if (savedWidths) {
      applySavedWidths(tableEl, savedWidths);
    }
    this.setupResizer(tableEl);
  }
  setupResizer(tableEl) {
    const tableId = getTableId(tableEl);
    makeTableResizable(this, tableEl, (widths) => {
      saveWidths(this, tableId, widths);
    });
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data == null ? void 0 : data.settings);
    this.widthStore = (data == null ? void 0 : data.columnWidths) || {};
  }
  async saveSettings() {
    await this.saveData({
      settings: this.settings,
      columnWidths: this.widthStore
    });
  }
};
