/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SheetExtendPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  minWidth: 50,
  maxWidth: 500,
  defaultWidth: 150,
  nativeProcessing: true,
  widthPersistence: "plugin",
  pixelsPerDash: 8
};
var SheetExtendSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  get settings() {
    return this.plugin.settings;
  }
  async updateSettings(changes) {
    Object.assign(this.plugin.settings, changes);
    await this.plugin.saveSettings();
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Sheet Extend Settings" });
    new import_obsidian.Setting(containerEl).setName("Minimum column width").setDesc("Minimum width for a resized column (px)").addSlider(
      (slider) => slider.setLimits(30, 100, 5).setValue(this.settings.minWidth).onChange(async (value) => {
        await this.updateSettings({ minWidth: value });
      })
    );
    new import_obsidian.Setting(containerEl).setName("Maximum column width").setDesc("Maximum width for a resized column (px)").addSlider(
      (slider) => slider.setLimits(200, 800, 10).setValue(this.settings.maxWidth).onChange(async (value) => {
        await this.updateSettings({ maxWidth: value });
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default column width").setDesc("Default column width when resized (px)").addSlider(
      (slider) => slider.setLimits(80, 300, 5).setValue(this.settings.defaultWidth).onChange(async (value) => {
        await this.updateSettings({ defaultWidth: value });
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable native table processing").setDesc("Automatically process all markdown tables (not just sheet code blocks)").addToggle(
      (toggle) => toggle.setValue(this.settings.nativeProcessing).onChange(async (value) => {
        await this.updateSettings({ nativeProcessing: value });
      })
    );
    new import_obsidian.Setting(containerEl).setName("Store column widths in Markdown").setDesc("Write resized column widths into the table separator row using dash counts").addToggle(
      (toggle) => toggle.setValue(this.settings.widthPersistence === "markdown").onChange(async (value) => {
        await this.updateSettings({ widthPersistence: value ? "markdown" : "plugin" });
      })
    );
    new import_obsidian.Setting(containerEl).setName("Pixels per separator dash").setDesc("Used when storing column widths in Markdown").addSlider(
      (slider) => slider.setLimits(4, 20, 1).setValue(this.settings.pixelsPerDash).onChange(async (value) => {
        await this.updateSettings({ pixelsPerDash: value });
      })
    );
  }
};

// src/sheet/detect.ts
function hasMergeMarkers(text) {
  const lines = text.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed.includes("|"))
      continue;
    if (/^\|?(\s*:?-{3,}:?\s*\|)+\s*:?-{3,}:?\s*\|?$/.test(trimmed))
      continue;
    const inner = trimmed.startsWith("|") ? trimmed.slice(1) : trimmed;
    const stripped = inner.endsWith("|") ? inner.slice(0, -1) : inner;
    const cells = stripped.split("|").map((c) => c.trim());
    for (const cell of cells) {
      if (isMergeMarkerCell(cell)) {
        return true;
      }
    }
  }
  return false;
}
function isMergeLeftMarker(value) {
  const text = (value || "").trim();
  return text === "<" || text === "<!-- sheet-extend:merge-left -->";
}
function isMergeUpMarker(value) {
  const text = (value || "").trim();
  return text === "^" || text === "<!-- sheet-extend:merge-up -->";
}
function isMergeMarkerCell(value) {
  return isMergeLeftMarker(value) || isMergeUpMarker(value);
}
function hasMergeMarkersInElement(tableEl) {
  for (const cell of Array.from(tableEl.querySelectorAll("th, td"))) {
    const text = (cell.textContent || "").trim();
    if (isMergeMarkerCell(text)) {
      return true;
    }
  }
  return false;
}

// src/sheet/parser.ts
function parseTable(text) {
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
  if (lines.length < 2) {
    return { grid: [], alignments: [] };
  }
  const rawRows = lines.map((line) => {
    const inner = line.startsWith("|") ? line.slice(1) : line;
    const trimmed = inner.endsWith("|") ? inner.slice(0, -1) : inner;
    return trimmed.split("|").map((c) => c.trim());
  });
  let delimIdx = -1;
  for (let i = 1; i < rawRows.length; i++) {
    if (rawRows[i].every((c) => /^:?-{3,}:?$/.test(c))) {
      delimIdx = i;
      break;
    }
  }
  const alignments = [];
  if (delimIdx >= 0) {
    for (const cell of rawRows[delimIdx]) {
      const left = cell.startsWith(":");
      const right = cell.endsWith(":");
      if (left && right)
        alignments.push("center");
      else if (right)
        alignments.push("right");
      else if (left)
        alignments.push("left");
      else
        alignments.push("default");
    }
  }
  const dataRows = delimIdx >= 0 ? rawRows.slice(delimIdx + 1) : rawRows.slice(1);
  const headerRows = delimIdx > 0 ? rawRows.slice(0, delimIdx) : [rawRows[0]];
  const colCount = Math.max(...dataRows.map((r) => r.length), ...headerRows.map((r) => r.length));
  const verticalHeaderCols = Array(colCount).fill(true);
  for (const row of dataRows) {
    for (let c = 0; c < colCount; c++) {
      const cell = (c < row.length ? row[c] : "").replace(/[`*_~]/g, "");
      if (cell !== "" && !/^:?-{3,}:?$/.test(cell)) {
        verticalHeaderCols[c] = false;
      }
    }
  }
  const grid = [];
  for (const row of headerRows) {
    const gridRow = [];
    for (let c = 0; c < colCount; c++) {
      const text2 = c < row.length ? row[c] : "";
      const cell = { text: text2, colspan: 1, rowspan: 1, hidden: false, isHeader: true };
      gridRow.push(cell);
    }
    grid.push(gridRow);
  }
  for (const row of dataRows) {
    const gridRow = [];
    for (let c = 0; c < colCount; c++) {
      const text2 = c < row.length ? row[c] : "";
      const isHeader = verticalHeaderCols[c] || false;
      const cell = { text: text2, colspan: 1, rowspan: 1, hidden: false, isHeader };
      gridRow.push(cell);
    }
    grid.push(gridRow);
  }
  return { grid, alignments };
}
function applyMerges(grid) {
  for (let r = 0; r < grid.length; r++) {
    const extendedVertically = /* @__PURE__ */ new Set();
    for (let c = 0; c < grid[r].length; c++) {
      const cell = grid[r][c];
      if (cell.hidden)
        continue;
      if (isMergeLeftMarker(cell.text) && c > 0) {
        const anchor = findAnchor(grid, r, c - 1, "horizontal");
        if (anchor && canExpand(grid, anchor, r, c, "horizontal")) {
          anchor.cell.colspan = Math.max(anchor.cell.colspan || 1, c - anchor.col + 1);
          hideCoveredCells(grid, anchor, r, c, "horizontal");
          cell.hidden = true;
        }
      } else if (isMergeUpMarker(cell.text) && r > 0) {
        const anchor = findAnchor(grid, r, c, "vertical");
        if (anchor && canExpand(grid, anchor, r, c, "vertical")) {
          if (!extendedVertically.has(anchor.cell)) {
            anchor.cell.rowspan = (anchor.cell.rowspan || 1) + 1;
            extendedVertically.add(anchor.cell);
          }
          hideCoveredCells(grid, anchor, r, c, "vertical");
          cell.hidden = true;
        }
      }
    }
  }
}
function findAnchor(grid, row, col, direction) {
  for (let r = row; r >= 0; r--) {
    for (let c = 0; c < grid[r].length; c++) {
      const candidate = grid[r][c];
      if (candidate.hidden)
        continue;
      const coversRow = direction === "vertical" ? r < row && r + (candidate.rowspan || 1) >= row : r <= row && row < r + (candidate.rowspan || 1);
      const coversCol = c <= col && col < c + (candidate.colspan || 1);
      if (!coversRow || !coversCol)
        continue;
      if (direction === "vertical" && r === row)
        continue;
      return { cell: candidate, row: r, col: c };
    }
  }
  return null;
}
function canExpand(grid, anchor, targetRow, targetCol, direction) {
  var _a;
  const rowEnd = direction === "vertical" ? targetRow : anchor.row + (anchor.cell.rowspan || 1) - 1;
  const colEnd = direction === "horizontal" ? targetCol : anchor.col + (anchor.cell.colspan || 1) - 1;
  for (let row = anchor.row; row <= rowEnd; row++) {
    for (let col = anchor.col; col <= colEnd; col++) {
      if (row === anchor.row && col === anchor.col)
        continue;
      const occupant = (_a = grid[row]) == null ? void 0 : _a[col];
      if (!occupant || occupant.hidden || isMergeMarkerCell(occupant.text))
        continue;
      if (row < anchor.row + (anchor.cell.rowspan || 1) && col < anchor.col + (anchor.cell.colspan || 1))
        continue;
      return false;
    }
  }
  return true;
}
function hideCoveredCells(grid, anchor, targetRow, targetCol, direction) {
  var _a;
  const rowEnd = direction === "vertical" ? targetRow : anchor.row + (anchor.cell.rowspan || 1) - 1;
  const colEnd = direction === "horizontal" ? targetCol : anchor.col + (anchor.cell.colspan || 1) - 1;
  for (let row = anchor.row; row <= rowEnd; row++) {
    for (let col = anchor.col; col <= colEnd; col++) {
      const occupant = (_a = grid[row]) == null ? void 0 : _a[col];
      if (!occupant || occupant === anchor.cell)
        continue;
      if (occupant.text.trim() === "" || isMergeMarkerCell(occupant.text))
        occupant.hidden = true;
    }
  }
}
function stripMergeMarkers(grid) {
  for (const row of grid) {
    for (const cell of row) {
      if (!cell.hidden) {
        const trimmed = cell.text.trim();
        if (isMergeMarkerCell(trimmed)) {
          cell.text = "";
        }
      }
    }
  }
}
function parseAndMerge(text) {
  const result = parseTable(text);
  applyMerges(result.grid);
  stripMergeMarkers(result.grid);
  return result;
}

// src/sheet/renderer.ts
var import_obsidian2 = require("obsidian");
function hasRowspanAcrossBoundary(grid, headerCount) {
  for (let r = 0; r < headerCount; r++) {
    for (const cell of grid[r]) {
      if (!cell.hidden && cell.rowspan > 1 && r + cell.rowspan > headerCount) {
        return true;
      }
    }
  }
  return false;
}
function renderTable(app, tableEl, parsed, sourcePath, component) {
  const { grid, alignments } = parsed;
  tableEl.empty();
  tableEl.classList.add("sheet-extend-parsed");
  tableEl.removeAttribute("data-resizable");
  if (grid.length === 0)
    return;
  const colCount = Math.max(...grid.map((row) => row.length));
  const colgroup = tableEl.createEl("colgroup");
  for (let i = 0; i < colCount; i++) {
    const col = colgroup.createEl("col");
    if (alignments[i]) {
      col.setAttribute("data-align", alignments[i]);
    }
  }
  const headerCount = 1;
  const crossBoundary = hasRowspanAcrossBoundary(grid, headerCount);
  if (crossBoundary) {
    const tbody = tableEl.createEl("tbody");
    for (let r = 0; r < grid.length; r++) {
      const row = grid[r];
      const tr = tbody.createEl("tr");
      for (let c = 0; c < row.length; c++) {
        const cell = row[c];
        if (cell.hidden)
          continue;
        const tag = cell.isHeader ? "th" : "td";
        const el = tr.createEl(tag);
        if (alignments[c]) {
          el.style.textAlign = alignments[c] === "default" ? "left" : alignments[c];
        }
        if (cell.colspan > 1)
          el.colSpan = cell.colspan;
        if (cell.rowspan > 1)
          el.rowSpan = cell.rowspan;
        el.setAttribute("data-row", String(r));
        el.setAttribute("data-col", String(c));
        import_obsidian2.MarkdownRenderer.render(app, cell.text, el, sourcePath, component);
      }
    }
  } else {
    const headerRows = grid.slice(0, headerCount);
    const dataRows = grid.slice(headerCount);
    if (headerRows.length > 0) {
      const thead = tableEl.createEl("thead");
      for (const row of headerRows) {
        const tr = thead.createEl("tr");
        for (let c = 0; c < row.length; c++) {
          const cell = row[c];
          if (cell.hidden)
            continue;
          const th = tr.createEl("th");
          if (alignments[c]) {
            th.style.textAlign = alignments[c] === "default" ? "left" : alignments[c];
          }
          if (cell.colspan > 1)
            th.colSpan = cell.colspan;
          if (cell.rowspan > 1)
            th.rowSpan = cell.rowspan;
          th.setAttribute("data-row", "0");
          th.setAttribute("data-col", String(c));
          import_obsidian2.MarkdownRenderer.render(app, cell.text, th, sourcePath, component);
        }
      }
    }
    if (dataRows.length > 0) {
      const tbody = tableEl.createEl("tbody");
      for (let r = 0; r < dataRows.length; r++) {
        const tr = tbody.createEl("tr");
        for (let c = 0; c < dataRows[r].length; c++) {
          const cell = dataRows[r][c];
          if (cell.hidden)
            continue;
          const tag = cell.isHeader ? "th" : "td";
          const td = tr.createEl(tag);
          if (alignments[c]) {
            td.style.textAlign = alignments[c] === "default" ? "left" : alignments[c];
          }
          if (cell.colspan > 1)
            td.colSpan = cell.colspan;
          if (cell.rowspan > 1)
            td.rowSpan = cell.rowspan;
          td.setAttribute("data-row", String(r + 1));
          td.setAttribute("data-col", String(c));
          import_obsidian2.MarkdownRenderer.render(app, cell.text, td, sourcePath, component);
        }
      }
    }
  }
}

// src/sheet/utils.ts
function getLineEnding(text) {
  return text.includes("\r\n") ? "\r\n" : "\n";
}
function splitLines(text) {
  return text.split(/\r?\n/);
}
var isTableLine = (line) => {
  const trimmed = line.trim();
  return trimmed.startsWith("|") && trimmed.endsWith("|") && trimmed.length > 1;
};
function normalizeSelection(selection) {
  return {
    rowStart: Math.min(selection.anchor.row, selection.focus.row),
    rowEnd: Math.max(selection.anchor.row, selection.focus.row),
    colStart: Math.min(selection.anchor.col, selection.focus.col),
    colEnd: Math.max(selection.anchor.col, selection.focus.col)
  };
}
function selectionHasHorizontalSpan(selection) {
  const bounds = normalizeSelection(selection);
  return bounds.colEnd > bounds.colStart;
}
function selectionHasVerticalSpan(selection) {
  const bounds = normalizeSelection(selection);
  return bounds.rowEnd > bounds.rowStart;
}
function getTableBounds(tableEl) {
  let maxRow = 0;
  let maxCol = 0;
  for (const cell of Array.from(tableEl.querySelectorAll("th, td"))) {
    const row = Number(cell.getAttribute("data-row"));
    const col = Number(cell.getAttribute("data-col"));
    if (Number.isInteger(row))
      maxRow = Math.max(maxRow, row);
    if (Number.isInteger(col))
      maxCol = Math.max(maxCol, col + (cell.colSpan || 1) - 1);
  }
  return { maxRow, maxCol };
}
function expandSelectionForDirection(tableEl, selection, direction) {
  if (direction === "horizontal" && selectionHasHorizontalSpan(selection))
    return selection;
  if (direction === "vertical" && selectionHasVerticalSpan(selection))
    return selection;
  const { maxRow, maxCol } = getTableBounds(tableEl);
  if (direction === "horizontal" && selection.focus.col < maxCol) {
    return { anchor: selection.anchor, focus: { row: selection.focus.row, col: selection.focus.col + 1 } };
  }
  if (direction === "vertical" && selection.focus.row < maxRow) {
    return { anchor: selection.anchor, focus: { row: selection.focus.row + 1, col: selection.focus.col } };
  }
  return null;
}
function expandSelectionForUnmerge(tableEl, selection) {
  const bounds = {
    rowStart: Math.min(selection.anchor.row, selection.focus.row),
    rowEnd: Math.max(selection.anchor.row, selection.focus.row),
    colStart: Math.min(selection.anchor.col, selection.focus.col),
    colEnd: Math.max(selection.anchor.col, selection.focus.col)
  };
  for (const cell of Array.from(tableEl.querySelectorAll("th, td"))) {
    const row = Number(cell.getAttribute("data-row"));
    const col = Number(cell.getAttribute("data-col"));
    if (!Number.isInteger(row) || !Number.isInteger(col))
      continue;
    const rowEnd = row + (cell.rowSpan || 1) - 1;
    const colEnd = col + (cell.colSpan || 1) - 1;
    if (!(row <= bounds.rowEnd && rowEnd >= bounds.rowStart && col <= bounds.colEnd && colEnd >= bounds.colStart))
      continue;
    bounds.rowStart = Math.min(bounds.rowStart, row);
    bounds.rowEnd = Math.max(bounds.rowEnd, rowEnd);
    bounds.colStart = Math.min(bounds.colStart, col);
    bounds.colEnd = Math.max(bounds.colEnd, colEnd);
  }
  return {
    anchor: { row: bounds.rowStart, col: bounds.colStart },
    focus: { row: bounds.rowEnd, col: bounds.colEnd }
  };
}

// src/sheet/markdown-table.ts
var splitMarkdownLines = splitLines;
var isMarkdownTableLine = isTableLine;
function splitMarkdownRow(line) {
  if (!line.includes("|"))
    return [];
  let normalized = line.trim();
  if (normalized.startsWith("|"))
    normalized = normalized.slice(1);
  if (normalized.endsWith("|"))
    normalized = normalized.slice(0, -1);
  return normalized.split("|").map((cell) => cell.trim());
}
function parseSeparatorLine(line) {
  const cells = splitMarkdownRow(line);
  if (!cells.length)
    return null;
  const columns = [];
  for (const cell of cells) {
    const match = cell.match(/^(:)?(-{3,})(:)?$/);
    if (!match)
      return null;
    columns.push({
      alignLeft: !!match[1],
      alignRight: !!match[3],
      dashCount: match[2].length
    });
  }
  return columns;
}
function buildSeparatorLine(columns, dashCounts) {
  return `| ${dashCounts.map((dashCount, index) => {
    const column = columns[index] || { alignLeft: false, alignRight: false, dashCount: 3 };
    const dashes = "-".repeat(Math.max(3, dashCount));
    return `${column.alignLeft ? ":" : ""}${dashes}${column.alignRight ? ":" : ""}`;
  }).join(" | ")} |`;
}
function extractMarkdownTableSpecs(markdown) {
  const lines = splitMarkdownLines(markdown);
  const lineEnding = getLineEnding(markdown);
  const specs = [];
  for (let separatorLine = 1; separatorLine < lines.length; separatorLine++) {
    const columns = parseSeparatorLine(lines[separatorLine]);
    if (!columns)
      continue;
    if (!isMarkdownTableLine(lines[separatorLine - 1]))
      continue;
    const headerLine = separatorLine - 1;
    const bodyLines = [];
    let endLine = separatorLine;
    for (let line = separatorLine + 1; line < lines.length; line++) {
      if (!isMarkdownTableLine(lines[line]))
        break;
      bodyLines.push(lines[line]);
      endLine = line;
    }
    const tableLines = lines.slice(headerLine, endLine + 1);
    specs.push({
      text: tableLines.join(lineEnding),
      range: { startLine: headerLine, endLine },
      tableOrdinal: specs.length,
      headerCells: splitMarkdownRow(lines[headerLine]),
      bodyLines,
      columns,
      rawHeaderLine: lines[headerLine],
      rawSeparatorLine: lines[separatorLine]
    });
    separatorLine = endLine;
  }
  return specs;
}
function normalizeSignatureCell(text) {
  return String(text || "").replace(/\[\[([^\]]*)\]\]/g, "$1").replace(/[*_`~]/g, "").replace(/\s+/g, " ").trim();
}
function markdownTableSignature(spec) {
  return [spec.headerCells, ...spec.bodyLines.map(splitMarkdownRow)].map((row) => row.map(normalizeSignatureCell).join("|")).join("\n");
}
function domTableSignature(tableEl) {
  return Array.from(tableEl.rows).map(
    (row) => Array.from(row.cells).map((cell) => normalizeSignatureCell(cell.textContent || "")).join("|")
  ).join("\n");
}
function uniqueSpecBySignature(specs, signature, buildSpecSignature) {
  if (!signature)
    return null;
  const matches = specs.filter((spec) => buildSpecSignature(spec) === signature);
  return matches.length === 1 ? matches[0] : null;
}
function domTableHeaderSignature(tableEl) {
  var _a;
  const headerRow = (_a = tableEl.rows) == null ? void 0 : _a[0];
  return (headerRow == null ? void 0 : headerRow.cells.length) ? Array.from(headerRow.cells).map((cell) => normalizeSignatureCell(cell.textContent)).join("|") : null;
}
function markdownTableHeaderSignature(spec) {
  return spec.headerCells.length ? spec.headerCells.map((cell) => normalizeSignatureCell(cell)).join("|") : null;
}
function domTableBodySignature(tableEl) {
  if (!(tableEl instanceof HTMLTableElement) || tableEl.rows.length < 2)
    return null;
  return Array.from(tableEl.rows).slice(1).map(
    (row) => Array.from(row.cells).map((cell) => normalizeSignatureCell(cell.textContent)).join("|")
  ).join("\n");
}
function markdownTableBodySignature(spec) {
  return spec.bodyLines.length ? spec.bodyLines.map((line) => splitMarkdownRow(line).map((cell) => normalizeSignatureCell(cell)).join("|")).join("\n") : null;
}
function domTableContentSignature(tableEl) {
  if (!(tableEl instanceof HTMLTableElement) || !tableEl.rows.length)
    return null;
  const rows = Array.from(tableEl.rows).map(
    (row) => Array.from(row.cells).map((cell) => normalizeSignatureCell(cell.textContent))
  );
  if (!rows.length || !rows[0].length)
    return null;
  const previewBody = rows.slice(1, 3).map((row) => row.join("|")).join("\n");
  return [rows.length, rows[0].length, rows[0].join("|"), previewBody].join("");
}
function markdownTableContentSignature(spec) {
  if (!spec.headerCells.length)
    return null;
  const previewBody = spec.bodyLines.slice(0, 2).map((line) => splitMarkdownRow(line).map((cell) => normalizeSignatureCell(cell)).join("|")).join("\n");
  return [
    1 + spec.bodyLines.length,
    spec.headerCells.length,
    spec.headerCells.map((cell) => normalizeSignatureCell(cell)).join("|"),
    previewBody
  ].join("");
}
function matchMarkdownTableSpecForElement(specs, tableEl, sourceLine = null) {
  var _a, _b;
  if (!specs.length || !(tableEl instanceof HTMLTableElement))
    return null;
  if (specs.length === 1)
    return specs[0];
  if (Number.isInteger(sourceLine) && sourceLine !== null) {
    const containing = specs.find(
      (spec) => sourceLine >= spec.range.startLine && sourceLine <= spec.range.endLine
    );
    if (containing)
      return containing;
  }
  const ordinal = Number.parseInt((_a = tableEl.dataset.sheetExtendTableOrdinal) != null ? _a : "", 10);
  if (Number.isInteger(ordinal) && ordinal >= 0 && specs[ordinal]) {
    return specs[ordinal];
  }
  const lineStart = Number.parseInt((_b = tableEl.getAttribute("data-line-start")) != null ? _b : "", 10);
  if (Number.isInteger(lineStart)) {
    const lineMatch = specs.find((spec) => spec.range.startLine === lineStart);
    if (lineMatch)
      return lineMatch;
  }
  const contentMatch = uniqueSpecBySignature(
    specs,
    domTableContentSignature(tableEl),
    markdownTableContentSignature
  );
  if (contentMatch)
    return contentMatch;
  const bodyMatch = uniqueSpecBySignature(
    specs,
    domTableBodySignature(tableEl),
    markdownTableBodySignature
  );
  if (bodyMatch)
    return bodyMatch;
  const headerMatch = uniqueSpecBySignature(
    specs,
    domTableHeaderSignature(tableEl),
    markdownTableHeaderSignature
  );
  if (headerMatch)
    return headerMatch;
  const exactMatch = uniqueSpecBySignature(
    specs,
    domTableSignature(tableEl),
    markdownTableSignature
  );
  if (exactMatch)
    return exactMatch;
  return null;
}
function buildSeparatorLineForWidths(separatorLine, widths, pixelsPerDash) {
  const columns = parseSeparatorLine(separatorLine);
  if (!columns)
    return null;
  const dashCounts = columns.map((column, index) => {
    const width = widths[index];
    if (typeof width !== "number" || Number.isNaN(width))
      return column.dashCount;
    return Math.max(3, Math.round(width / pixelsPerDash));
  });
  return buildSeparatorLine(columns, dashCounts);
}

// src/resizer/resizer.ts
function makeTableResizable(plugin, tableEl, callbacks) {
  var _a;
  if (tableEl.hasAttribute("data-resizable"))
    return;
  tableEl.setAttribute("data-resizable", "true");
  const resizeCallbacks = typeof callbacks === "function" ? { onResizeEnd: callbacks } : callbacks;
  const settings = plugin.settings;
  const cols = Array.from(tableEl.querySelectorAll("colgroup col"));
  if (cols.length === 0)
    return;
  const cells = Array.from(tableEl.querySelectorAll("th, td"));
  for (const cell of cells) {
    const startIndex = Number((_a = cell.getAttribute("data-col")) != null ? _a : cell.cellIndex);
    const index = startIndex + (cell.colSpan || 1) - 1;
    if (Number.isNaN(index) || index >= cols.length - 1)
      continue;
    cell.style.position = "relative";
    const handle = document.createElement("div");
    handle.className = "sheet-extend-resizer";
    cell.appendChild(handle);
    let startX = 0;
    let startWidth = 0;
    handle.addEventListener("mousedown", (e) => {
      var _a2;
      e.preventDefault();
      e.stopPropagation();
      startWidth = cols[index].offsetWidth || cols[index].getBoundingClientRect().width;
      startX = e.clientX;
      tableEl.setAttribute("data-resizing", "true");
      document.body.classList.add("sheet-extend-resizing");
      (_a2 = resizeCallbacks.onResizeStart) == null ? void 0 : _a2.call(resizeCallbacks);
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
      window.addEventListener("blur", onBlur);
    });
    const onBlur = () => {
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
      window.removeEventListener("blur", onBlur);
      tableEl.removeAttribute("data-resizing");
      document.body.classList.remove("sheet-extend-resizing");
    };
    const onMouseMove = (e) => {
      const diff = e.clientX - startX;
      const newWidth = Math.max(
        settings.minWidth,
        Math.min(settings.maxWidth, startWidth + diff)
      );
      cols[index].style.width = newWidth + "px";
      cols[index].style.minWidth = newWidth + "px";
      cols[index].style.maxWidth = newWidth + "px";
    };
    const onMouseUp = () => {
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
      window.removeEventListener("blur", onBlur);
      tableEl.removeAttribute("data-resizing");
      document.body.classList.remove("sheet-extend-resizing");
      const widths = cols.map(
        (col) => col.style.width ? parseInt(col.style.width) : null
      );
      resizeCallbacks.onResizeEnd(widths);
    };
  }
}

// src/resizer/persistence.ts
var DATA_VERSION = "1.5.0";
function getTableIds(tableEl) {
  const sourcePath = tableEl.getAttribute("data-source-path");
  const lineStart = tableEl.getAttribute("data-line-start");
  const ordinal = tableEl.dataset.sheetExtendTableOrdinal;
  const ids = [];
  if (sourcePath && lineStart) {
    ids.push(`table-${sourcePath}-${lineStart}`);
  }
  if (sourcePath && ordinal) {
    ids.push(`table-${sourcePath}-ordinal-${ordinal}`);
  }
  if (sourcePath && Number.isInteger(Number(ordinal))) {
    ids.push(`table-${sourcePath}-ordinal-${ordinal}-fallback`);
  }
  return Array.from(new Set(ids));
}
function saveWidths(plugin, tableId, widths) {
  const store = plugin.widthStore || {};
  const tableIds = Array.isArray(tableId) ? tableId : [tableId];
  const hasData = widths.some((w) => w !== null);
  for (const id of tableIds) {
    if (hasData) {
      store[id] = widths;
    } else {
      delete store[id];
    }
  }
  plugin.widthStore = store;
  plugin.saveData({
    version: DATA_VERSION,
    settings: plugin.settings,
    columnWidths: store
  });
}
function loadWidths(plugin, tableId) {
  const store = plugin.widthStore || {};
  const tableIds = Array.isArray(tableId) ? tableId : [tableId];
  for (const id of tableIds) {
    if (store[id]) {
      return store[id];
    }
  }
  return null;
}
function applySavedWidths(tableEl, widths) {
  const cols = tableEl.querySelectorAll("colgroup col");
  for (let i = 0; i < cols.length && i < widths.length; i++) {
    const w = widths[i];
    if (w !== null) {
      const col = cols[i];
      col.style.width = w + "px";
      col.style.minWidth = w + "px";
      col.style.maxWidth = w + "px";
    }
  }
}

// src/merge/interaction.ts
var import_obsidian3 = require("obsidian");

// src/sheet/writeback.ts
function isDelimiterCell(cell) {
  return /^:?-{3,}:?$/.test(cell.trim());
}
function parseLine(line) {
  const trimmed = line.trim();
  const hasLeadingPipe = trimmed.startsWith("|");
  const hasTrailingPipe = trimmed.endsWith("|");
  let inner = hasLeadingPipe ? trimmed.slice(1) : trimmed;
  if (hasTrailingPipe)
    inner = inner.slice(0, -1);
  return {
    cells: inner.split("|").map((cell) => cell.trim()),
    hasLeadingPipe,
    hasTrailingPipe
  };
}
function serializeLine(parsed) {
  const body = ` ${parsed.cells.join(" | ")} `;
  if (parsed.hasLeadingPipe && parsed.hasTrailingPipe)
    return `|${body}|`;
  if (parsed.hasLeadingPipe)
    return `|${body}`;
  if (parsed.hasTrailingPipe)
    return `${body}|`;
  return body.trim();
}
function parseTableLines(lines) {
  const parsed = lines.map(parseLine);
  const delimiterIndex = parsed.findIndex((line, index) => index > 0 && line.cells.length > 0 && line.cells.every(isDelimiterCell));
  return { parsed, delimiterIndex };
}
function markdownLineForGridRow(gridRow, delimiterIndex) {
  if (delimiterIndex < 0)
    return gridRow;
  return gridRow < delimiterIndex ? gridRow : gridRow + 1;
}
function ensureColumn(line, col) {
  while (line.cells.length <= col) {
    line.cells.push("");
  }
}
function isMergeMarker(value) {
  return isMergeMarkerCell(value);
}
var HIDDEN_MERGE_LEFT = "<!-- sheet-extend:merge-left -->";
var HIDDEN_MERGE_UP = "<!-- sheet-extend:merge-up -->";
function applyMergeMarkers(tableText, selection, direction) {
  const lines = splitLines(tableText);
  const lineEnding = getLineEnding(tableText);
  const { parsed, delimiterIndex } = parseTableLines(lines);
  const normalized = normalizeSelection(selection);
  if (normalized.rowStart === normalized.rowEnd && normalized.colStart === normalized.colEnd) {
    return tableText;
  }
  for (let row = normalized.rowStart; row <= normalized.rowEnd; row++) {
    const lineIndex = markdownLineForGridRow(row, delimiterIndex);
    const line = parsed[lineIndex];
    if (!line)
      continue;
    if (row === normalized.rowStart && isMergeMarker(line.cells[normalized.colStart])) {
      return tableText;
    }
    const selectedColStart = normalized.colStart;
    const selectedColEnd = normalized.colEnd;
    for (let col = selectedColStart; col <= selectedColEnd; col++) {
      ensureColumn(line, col);
      const isAnchor = row === normalized.rowStart && col === normalized.colStart;
      if (isAnchor)
        continue;
      if (direction === "horizontal" && row === normalized.rowStart) {
        line.cells[col] = HIDDEN_MERGE_LEFT;
      } else if (direction === "vertical" && col === normalized.colStart) {
        line.cells[col] = HIDDEN_MERGE_UP;
      }
    }
  }
  return parsed.map(serializeLine).join(lineEnding);
}
function clearMergeMarkers(tableText, selection) {
  const lines = splitLines(tableText);
  const lineEnding = getLineEnding(tableText);
  const { parsed, delimiterIndex } = parseTableLines(lines);
  const normalized = normalizeSelection(selection);
  for (let row = normalized.rowStart; row <= normalized.rowEnd; row++) {
    const lineIndex = markdownLineForGridRow(row, delimiterIndex);
    const line = parsed[lineIndex];
    if (!line)
      continue;
    for (let col = normalized.colStart; col <= normalized.colEnd; col++) {
      if (isMergeMarker(line.cells[col])) {
        line.cells[col] = "";
      }
    }
  }
  return parsed.map(serializeLine).join(lineEnding);
}
function replaceTableRange(documentText, range, tableText) {
  const lines = splitLines(documentText);
  const lineEnding = getLineEnding(documentText);
  lines.splice(range.startLine, range.endLine - range.startLine + 1, ...splitLines(tableText));
  return lines.join(lineEnding);
}
function applyMergeToDocument(documentText, range, selection, direction) {
  const lineEnding = getLineEnding(documentText);
  const tableText = splitLines(documentText).slice(range.startLine, range.endLine + 1).join(lineEnding);
  const nextTableText = applyMergeMarkers(tableText, selection, direction);
  return {
    text: replaceTableRange(documentText, range, nextTableText),
    range
  };
}
function clearMergeInDocument(documentText, range, selection) {
  const lineEnding = getLineEnding(documentText);
  const tableText = splitLines(documentText).slice(range.startLine, range.endLine + 1).join(lineEnding);
  const nextTableText = clearMergeMarkers(tableText, selection);
  return {
    text: replaceTableRange(documentText, range, nextTableText),
    range
  };
}

// src/merge/interaction.ts
function getCellPosition(cell) {
  const row = Number(cell.getAttribute("data-row"));
  const col = Number(cell.getAttribute("data-col"));
  if (!Number.isInteger(row) || !Number.isInteger(col))
    return null;
  return { row, col };
}
function containsPosition(selection, position) {
  const bounds = normalizeSelection(selection);
  return position.row >= bounds.rowStart && position.row <= bounds.rowEnd && position.col >= bounds.colStart && position.col <= bounds.colEnd;
}
function getEditor(app) {
  const view = app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
  return (view == null ? void 0 : view.editor) || null;
}
function replaceTableInEditor(editor, range, oldDoc, newDoc) {
  var _a, _b;
  const oldLines = oldDoc.split("\n");
  const newLines = newDoc.split("\n");
  const newTableText = newLines.slice(range.startLine, range.endLine + 1).join("\n");
  editor.replaceRange(
    newTableText,
    { line: range.startLine, ch: 0 },
    { line: range.endLine, ch: (_b = (_a = oldLines[range.endLine]) == null ? void 0 : _a.length) != null ? _b : 0 }
  );
  editor.setCursor({ line: range.startLine, ch: 0 });
}
var MergeInteraction = class {
  constructor(host, tableEl) {
    this.host = host;
    this.tableEl = tableEl;
    this.selection = null;
    this.handleClick = (evt) => {
      const target = evt.target;
      if (target.closest(".sheet-extend-resizer"))
        return;
      const cell = target.closest("th, td");
      if (!cell || !this.tableEl.contains(cell))
        return;
      const position = getCellPosition(cell);
      if (!position)
        return;
      if (evt.shiftKey && this.selection) {
        this.selection = { anchor: this.selection.anchor, focus: position };
      } else {
        this.selection = { anchor: position, focus: position };
      }
      this.host.setActiveSelection({ tableEl: this.tableEl, selection: this.selection });
      this.paintSelection();
    };
    this.handleContextMenu = (evt) => {
      const cell = evt.target.closest("th, td");
      if (!cell || !this.tableEl.contains(cell))
        return;
      const position = getCellPosition(cell);
      if (!position)
        return;
      if (!this.selection || !containsPosition(this.selection, position)) {
        this.selection = { anchor: position, focus: position };
        this.paintSelection();
      }
      this.host.setActiveSelection({ tableEl: this.tableEl, selection: this.selection });
      evt.preventDefault();
      this.showMenu(evt);
    };
    this.tableEl.classList.add("sheet-extend-merge-enabled");
    this.host.component.registerDomEvent(this.tableEl, "click", this.handleClick);
    this.host.component.registerDomEvent(this.tableEl, "contextmenu", this.handleContextMenu);
  }
  getSelection() {
    return this.selection;
  }
  merge(direction) {
    if (!this.selection)
      return false;
    const selection = expandSelectionForDirection(this.tableEl, this.selection, direction);
    if (!selection)
      return false;
    this.writeSelection((doc, range) => applyMergeToDocument(doc, range, selection, direction).text);
    return true;
  }
  unmerge() {
    if (!this.selection)
      return false;
    const selection = expandSelectionForUnmerge(this.tableEl, this.selection);
    this.writeSelection((doc, range) => clearMergeInDocument(doc, range, selection).text);
    return true;
  }
  showMenu(evt) {
    const selection = this.selection;
    if (!selection)
      return;
    const menu = new import_obsidian3.Menu();
    const horizontalSelection = expandSelectionForDirection(this.tableEl, selection, "horizontal");
    const verticalSelection = expandSelectionForDirection(this.tableEl, selection, "vertical");
    menu.addItem((item) => {
      item.setTitle("Merge selected cells horizontally (Mod+Shift+Right)").setIcon("columns-3").setDisabled(!horizontalSelection).onClick(() => this.merge("horizontal"));
    });
    menu.addItem((item) => {
      item.setTitle("Merge selected cells vertically (Mod+Shift+Down)").setIcon("rows-3").setDisabled(!verticalSelection).onClick(() => this.merge("vertical"));
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("Unmerge selected cells (Mod+Shift+Left)").setIcon("split-square-horizontal").onClick(() => this.unmerge());
    });
    menu.showAtMouseEvent(evt);
  }
  paintSelection() {
    const selection = this.selection;
    for (const cell of Array.from(this.tableEl.querySelectorAll("th, td"))) {
      const position = getCellPosition(cell);
      const selected = !!selection && !!position && containsPosition(selection, position);
      cell.toggleClass("sheet-extend-cell-selected", selected);
    }
  }
  writeSelection(getNextDocument) {
    var _a, _b;
    if (!this.selection)
      return;
    const editor = getEditor(this.host.app);
    const range = this.host.getTableRange(this.tableEl);
    if (!editor || !range)
      return;
    const oldDoc = editor.getValue();
    const newDoc = getNextDocument(oldDoc, range, this.selection);
    replaceTableInEditor(editor, range, oldDoc, newDoc);
    (_b = (_a = this.host).onDocumentChanged) == null ? void 0 : _b.call(_a);
  }
};
function installMergeInteraction(host, tableEl) {
  const registered = tableEl;
  if (registered.sheetExtendMergeInteraction)
    return;
  registered.sheetExtendMergeInteraction = new MergeInteraction(host, tableEl);
}
function runMergeCommand(app, direction, range, selection) {
  const editor = getEditor(app);
  if (!editor || !range || !selection)
    return false;
  const oldDoc = editor.getValue();
  const newDoc = applyMergeToDocument(oldDoc, range, selection, direction).text;
  replaceTableInEditor(editor, range, oldDoc, newDoc);
  return true;
}
function runUnmergeCommand(app, range, selection) {
  const editor = getEditor(app);
  if (!editor || !range || !selection)
    return false;
  const oldDoc = editor.getValue();
  const newDoc = clearMergeInDocument(oldDoc, range, selection).text;
  replaceTableInEditor(editor, range, oldDoc, newDoc);
  return true;
}

// src/sheet/live-preview.ts
function addCellCoordinates(tableEl) {
  const occupied = /* @__PURE__ */ new Map();
  for (let rowIndex = 0; rowIndex < tableEl.rows.length; rowIndex++) {
    const row = tableEl.rows[rowIndex];
    let logicalCol = 0;
    for (const cell of Array.from(row.cells)) {
      while (occupied.has(`${rowIndex}:${logicalCol}`))
        logicalCol++;
      cell.setAttribute("data-row", String(rowIndex));
      cell.setAttribute("data-col", String(logicalCol));
      for (let r = 0; r < (cell.rowSpan || 1); r++) {
        for (let c = 0; c < (cell.colSpan || 1); c++) {
          occupied.set(`${rowIndex + r}:${logicalCol + c}`, true);
        }
      }
      logicalCol += cell.colSpan || 1;
    }
  }
}
function flattenSections(tableEl) {
  const thead = tableEl.tHead;
  if (!thead || !tableEl.tBodies.length)
    return;
  const tbody = tableEl.tBodies[0];
  tbody.prepend(...Array.from(thead.rows));
  thead.remove();
}
function ensureLogicalColumns(tableEl, parsed) {
  var _a, _b;
  for (let rowIndex = 0; rowIndex < tableEl.rows.length; rowIndex++) {
    const row = tableEl.rows[rowIndex];
    const target = ((_a = parsed.grid[rowIndex]) == null ? void 0 : _a.length) || 0;
    const current = Array.from(row.cells).reduce((sum, cell) => sum + (cell.colSpan || 1), 0);
    const tag = ((_b = row.parentElement) == null ? void 0 : _b.tagName) === "THEAD" ? "th" : "td";
    for (let col = current; col < target; col++)
      row.appendChild(tableEl.ownerDocument.createElement(tag));
  }
}
function applyLivePreviewMerge(tableEl, parsed) {
  var _a;
  const headerRows = ((_a = tableEl.tHead) == null ? void 0 : _a.rows.length) || 0;
  const crossesSections = !!tableEl.tHead && tableEl.tBodies.length > 0 && parsed.grid.slice(0, headerRows || 1).some((row, index) => row.some((cell) => !cell.hidden && cell.rowspan > 1 && index + cell.rowspan > headerRows));
  if (crossesSections)
    flattenSections(tableEl);
  for (const cell of Array.from(tableEl.querySelectorAll("th, td"))) {
    cell.style.display = "";
    cell.colSpan = 1;
    cell.rowSpan = 1;
  }
  ensureLogicalColumns(tableEl, parsed);
  addCellCoordinates(tableEl);
  const cells = /* @__PURE__ */ new Map();
  for (const cell of Array.from(tableEl.querySelectorAll("th, td"))) {
    cells.set(`${cell.getAttribute("data-row")}:${cell.getAttribute("data-col")}`, cell);
  }
  for (let row = 0; row < parsed.grid.length; row++) {
    for (let col = 0; col < parsed.grid[row].length; col++) {
      const parsedCell = parsed.grid[row][col];
      const domCell = cells.get(`${row}:${col}`);
      if (!domCell)
        continue;
      if (parsedCell.hidden) {
        domCell.style.display = "none";
        domCell.textContent = "";
      } else {
        domCell.colSpan = parsedCell.colspan || 1;
        domCell.rowSpan = parsedCell.rowspan || 1;
        if (parsedCell.text === "" && isMergeMarkerCell(domCell.textContent || "")) {
          domCell.textContent = "";
        }
      }
    }
  }
  return crossesSections;
}

// src/sheet/source-view.ts
function selectSourceView(active, leaves, sourcePath) {
  var _a, _b;
  if (!sourcePath || ((_a = active == null ? void 0 : active.file) == null ? void 0 : _a.path) === sourcePath)
    return active || null;
  return ((_b = leaves.find((leaf) => {
    var _a2, _b2;
    return ((_b2 = (_a2 = leaf.view) == null ? void 0 : _a2.file) == null ? void 0 : _b2.path) === sourcePath;
  })) == null ? void 0 : _b.view) || null;
}

// main.ts
function ensureColgroup(tableEl) {
  if (tableEl.querySelector("colgroup"))
    return;
  const colCount = getLogicalColumnCount(tableEl);
  if (colCount === 0)
    return;
  const colgroup = document.createElement("colgroup");
  for (let i = 0; i < colCount; i++) {
    colgroup.appendChild(document.createElement("col"));
  }
  tableEl.insertBefore(colgroup, tableEl.firstChild);
}
function getLogicalColumnCount(tableEl) {
  let colCount = 0;
  for (const row of Array.from(tableEl.rows)) {
    let width = 0;
    for (const cell of Array.from(row.cells)) {
      width += cell.colSpan || 1;
    }
    colCount = Math.max(colCount, width);
  }
  return colCount;
}
function isSourceModeTable(tableEl) {
  return !!tableEl.closest(".markdown-source-view, .cm-table-widget");
}
var SheetExtendPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.widthStore = {};
    this.tableRanges = /* @__PURE__ */ new WeakMap();
    this.activeMergeSelection = null;
    this.refreshTimer = null;
    this.observer = null;
    this.resizingTables = /* @__PURE__ */ new WeakSet();
    this.specsCache = null;
    this.pendingWidthsSave = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SheetExtendSettingTab(this.app, this));
    this.registerMarkdownPostProcessor((element, context) => {
      if (!this.settings.nativeProcessing)
        return;
      if (!this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView))
        return;
      const tables = Array.from(element.querySelectorAll("table:not(.sheet-extend-parsed)"));
      for (const tableEl of tables) {
        this.processTable(tableEl, context);
      }
    });
    this.registerMarkdownCodeBlockProcessor("sheet", (source, el, ctx) => {
      const parsed = parseAndMerge(source);
      const tableEl = el.createEl("table");
      renderTable(this.app, tableEl, parsed, ctx.sourcePath, this);
      this.setupResizer(tableEl);
      installMergeInteraction({
        app: this.app,
        component: this,
        getTableRange: (table) => this.tableRanges.get(table) || null,
        setActiveSelection: (context) => {
          this.activeMergeSelection = context;
        },
        onDocumentChanged: () => this.scheduleLivePreviewRefresh(0)
      }, tableEl);
    });
    this.addCommand({
      id: "merge-table-cells-horizontal",
      name: "Merge selected table cells horizontally",
      checkCallback: (checking) => this.runActiveMergeCommand(checking, "horizontal"),
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "ArrowRight" }]
    });
    this.addCommand({
      id: "merge-table-cells-vertical",
      name: "Merge selected table cells vertically",
      checkCallback: (checking) => this.runActiveMergeCommand(checking, "vertical"),
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "ArrowDown" }]
    });
    this.addCommand({
      id: "unmerge-table-cells",
      name: "Unmerge selected table cells",
      checkCallback: (checking) => this.runActiveUnmergeCommand(checking),
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "ArrowLeft" }]
    });
    this.registerEvent(this.app.workspace.on("editor-menu", (menu) => {
      this.addMergeItemsToEditorMenu(menu);
    }));
    this.registerEvent(this.app.workspace.on("layout-change", () => this.scheduleLivePreviewRefresh()));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.scheduleLivePreviewRefresh()));
    this.registerEvent(this.app.workspace.on("file-open", () => this.scheduleLivePreviewRefresh()));
    this.registerEvent(this.app.workspace.on("editor-change", () => this.scheduleLivePreviewRefresh()));
    this.registerDomEvent(window, "resize", () => this.scheduleLivePreviewRefresh());
    this.observeWorkspaceTables();
    this.scheduleLivePreviewRefresh();
  }
  /**
   * Extract the raw markdown source for a table from the editor document.
   * In Live Preview mode, getSectionInfo often returns null and the DOM
   * may have already processed special characters like ^ (footnote marker).
   * This method reads directly from the CM6 editor to get untouched source.
   */
  getSourceFromEditor() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!view)
      return null;
    const editor = view.editor;
    if (!editor)
      return null;
    return editor.getValue();
  }
  getMarkdownViewForSourcePath(sourcePath) {
    var _a, _b, _c;
    const active = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!sourcePath || ((_a = active == null ? void 0 : active.file) == null ? void 0 : _a.path) === sourcePath)
      return active || null;
    const leaves = ((_c = (_b = this.app.workspace).getLeavesOfType) == null ? void 0 : _c.call(_b, "markdown")) || [];
    return selectSourceView(active, leaves, sourcePath);
  }
  /**
   * Given the full document text, find the table block that contains
   * the approximate content matching the DOM table.
   * Returns the raw markdown table text or null if not found.
   */
  findMergeTableInDocument(docText, tableEl, sourcePath) {
    var _a;
    const hasSourceHint = tableEl.hasAttribute("data-line-start") || Number.isInteger(this.getSourceLineForTable(tableEl, sourcePath));
    if (!hasMergeMarkersInElement(tableEl) && !hasSourceHint) {
      return null;
    }
    const lines = splitMarkdownLines(docText);
    const tableBlocks = [];
    let inTable = false;
    let blockStart = -1;
    for (let i = 0; i < lines.length; i++) {
      if (isTableLine(lines[i]) && !inTable) {
        inTable = true;
        blockStart = i;
      } else if (!isTableLine(lines[i]) && inTable) {
        inTable = false;
        tableBlocks.push({ start: blockStart, end: i - 1 });
      }
    }
    if (inTable) {
      tableBlocks.push({ start: blockStart, end: lines.length - 1 });
    }
    if (tableBlocks.length === 0)
      return null;
    const domColCount = ((_a = tableEl.querySelector("tr")) == null ? void 0 : _a.children.length) || 0;
    for (const block of tableBlocks) {
      const blockText = lines.slice(block.start, block.end + 1).join("\n");
      if (hasMergeMarkers(blockText)) {
        const firstLine = lines[block.start];
        const colCount = (firstLine.match(/\|/g) || []).length - 1;
        if (domColCount === 0 || Math.abs(colCount - domColCount) <= 1) {
          return {
            text: blockText,
            range: { startLine: block.start, endLine: block.end },
            sourcePath
          };
        }
      }
    }
    return null;
  }
  getSourceLineForTable(tableEl, sourcePath = "") {
    const view = this.getMarkdownViewForSourcePath(sourcePath);
    const editor = view == null ? void 0 : view.editor;
    if (!(editor == null ? void 0 : editor.posAtDOM))
      return null;
    const candidates = [
      tableEl.closest(".cm-table-widget"),
      tableEl.querySelector("thead th"),
      tableEl.querySelector("tr th"),
      tableEl.querySelector("tr td"),
      tableEl
    ].filter(Boolean);
    for (const candidate of candidates) {
      for (const offset of [-1, 0, 1]) {
        try {
          const position = editor.posAtDOM(candidate, offset);
          if (position && Number.isInteger(position.line) && position.line >= 0) {
            return position.line;
          }
        } catch (_error) {
        }
      }
    }
    return null;
  }
  applyTableMatchMetadata(tableEl, match) {
    tableEl.setAttribute("data-source-path", match.sourcePath);
    tableEl.setAttribute("data-line-start", String(match.range.startLine));
    if (Number.isInteger(match.tableOrdinal)) {
      tableEl.dataset.sheetExtendTableOrdinal = String(match.tableOrdinal);
    }
  }
  processTable(tableEl, context) {
    if (!tableEl.isConnected)
      return;
    const match = this.resolveTableSource(tableEl, context);
    if (!match || !hasMergeMarkers(match.text)) {
      this.enhancePlainTable(tableEl, context, match);
      return;
    }
    if (isSourceModeTable(tableEl)) {
      this.enhanceSourceModeTable(tableEl, match);
      return;
    }
    const parsed = parseAndMerge(match.text);
    renderTable(this.app, tableEl, parsed, match.sourcePath, this);
    this.applyTableMatchMetadata(tableEl, match);
    this.tableRanges.set(tableEl, match.range);
    const tableId = getTableIds(tableEl);
    this.applyInitialWidths(tableEl, tableId, match.text);
    this.setupResizer(tableEl);
    this.setupMergeInteraction(tableEl);
  }
  enhanceSourceModeTable(tableEl, match) {
    this.applyTableMatchMetadata(tableEl, match);
    this.tableRanges.set(tableEl, match.range);
    ensureColgroup(tableEl);
    const tableId = getTableIds(tableEl);
    this.applyInitialWidths(tableEl, tableId, match.text);
    this.setupResizer(tableEl);
    this.addCellCoordinates(tableEl);
    this.applyMergePreviewToExistingTable(tableEl, match.text);
    this.setupMergeInteraction(tableEl);
  }
  applyMergePreviewToExistingTable(tableEl, tableText) {
    applyLivePreviewMerge(tableEl, parseAndMerge(tableText));
  }
  parsedTableHasRowspanAcrossDomSections(tableEl, parsed) {
    if (!tableEl.tHead || !tableEl.tBodies.length) {
      return false;
    }
    const headerRows = tableEl.tHead.rows.length || 1;
    for (let row = 0; row < Math.min(headerRows, parsed.grid.length); row++) {
      for (const cell of parsed.grid[row]) {
        if (!cell.hidden && cell.rowspan > 1 && row + cell.rowspan > headerRows) {
          return true;
        }
      }
    }
    return false;
  }
  resolveTableSource(tableEl, context) {
    let sourceText = "";
    let range = null;
    let tableOrdinal;
    if (context.getSectionInfo) {
      const sectionInfo = context.getSectionInfo(tableEl);
      if (sectionInfo) {
        const lines = splitMarkdownLines(sectionInfo.text);
        const sectionSpecs = extractMarkdownTableSpecs(sectionInfo.text);
        const matched = matchMarkdownTableSpecForElement(sectionSpecs, tableEl);
        if (matched) {
          const offset = sectionInfo.lineStart + matched.range.startLine;
          sourceText = matched.text;
          range = {
            startLine: offset,
            endLine: offset + (matched.range.endLine - matched.range.startLine)
          };
          tableOrdinal = matched.tableOrdinal;
        } else if (lines.length) {
          sourceText = sectionInfo.text;
          range = {
            startLine: sectionInfo.lineStart,
            endLine: sectionInfo.lineEnd
          };
        }
      }
    }
    if (!sourceText) {
      const view = this.getMarkdownViewForSourcePath(context.sourcePath || "");
      if (view && view.editor) {
        const fullDoc = view.editor.getValue();
        const match = this.findTableInSource(fullDoc, tableEl, context.sourcePath || "") || this.findMergeTableInDocument(fullDoc, tableEl, context.sourcePath || "");
        sourceText = (match == null ? void 0 : match.text) || "";
        range = (match == null ? void 0 : match.range) || null;
        tableOrdinal = match == null ? void 0 : match.tableOrdinal;
      }
    }
    if (!sourceText || !range)
      return null;
    return { text: sourceText, range, sourcePath: context.sourcePath || "", tableOrdinal };
  }
  enhancePlainTable(tableEl, context, existingMatch) {
    ensureColgroup(tableEl);
    const match = existingMatch || this.resolveTableSource(tableEl, context);
    if (match) {
      this.applyTableMatchMetadata(tableEl, match);
      this.tableRanges.set(tableEl, match.range);
    } else {
      const range = this.getRangeForPlainTable(tableEl);
      if (range) {
        this.tableRanges.set(tableEl, range);
      }
    }
    const tableId = getTableIds(tableEl);
    this.applyInitialWidths(tableEl, tableId, (match == null ? void 0 : match.text) || "");
    this.setupResizer(tableEl);
    this.addCellCoordinates(tableEl);
    this.setupMergeInteraction(tableEl);
  }
  addCellCoordinates(tableEl) {
    const occupied = /* @__PURE__ */ new Map();
    for (let rowIndex = 0; rowIndex < tableEl.rows.length; rowIndex++) {
      const row = tableEl.rows[rowIndex];
      let logicalCol = 0;
      for (const cell of Array.from(row.cells)) {
        while (occupied.has(`${rowIndex}:${logicalCol}`)) {
          logicalCol++;
        }
        cell.setAttribute("data-row", String(rowIndex));
        cell.setAttribute("data-col", String(logicalCol));
        for (let r = 0; r < (cell.rowSpan || 1); r++) {
          for (let c = 0; c < (cell.colSpan || 1); c++) {
            occupied.set(`${rowIndex + r}:${logicalCol + c}`, true);
          }
        }
        logicalCol += cell.colSpan || 1;
      }
    }
  }
  setupMergeInteraction(tableEl) {
    installMergeInteraction({
      app: this.app,
      component: this,
      getTableRange: (table) => this.tableRanges.get(table) || null,
      setActiveSelection: (context) => {
        this.activeMergeSelection = context;
      },
      onDocumentChanged: () => this.scheduleLivePreviewRefresh(0)
    }, tableEl);
  }
  getRangeForPlainTable(tableEl) {
    var _a;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!(view == null ? void 0 : view.editor))
      return null;
    const match = this.findTableInSource(view.editor.getValue(), tableEl, ((_a = view.file) == null ? void 0 : _a.path) || "");
    return (match == null ? void 0 : match.range) || null;
  }
  runActiveMergeCommand(checking, direction) {
    const active = this.activeMergeSelection;
    if (!active || !active.tableEl.isConnected)
      return false;
    const range = this.tableRanges.get(active.tableEl) || null;
    if (!range)
      return false;
    const selection = expandSelectionForDirection(active.tableEl, active.selection, direction);
    if (!selection)
      return false;
    if (!checking) {
      if (runMergeCommand(this.app, direction, range, selection)) {
        this.scheduleLivePreviewRefresh(0);
      }
    }
    return true;
  }
  addMergeItemsToEditorMenu(menu) {
    var _a;
    const active = this.activeMergeSelection;
    if (!active || !active.tableEl.isConnected)
      return;
    const range = this.tableRanges.get(active.tableEl) || null;
    if (!range)
      return;
    const horizontalSelection = expandSelectionForDirection(active.tableEl, active.selection, "horizontal");
    const verticalSelection = expandSelectionForDirection(active.tableEl, active.selection, "vertical");
    const unmergeSelection = expandSelectionForUnmerge(active.tableEl, active.selection);
    (_a = menu.addSeparator) == null ? void 0 : _a.call(menu);
    menu.addItem((item) => {
      item.setTitle("Merge selected cells horizontally").setIcon("columns-3").setDisabled(!horizontalSelection).onClick(() => {
        if (runMergeCommand(this.app, "horizontal", range, horizontalSelection)) {
          this.scheduleLivePreviewRefresh(0);
        }
      });
    });
    menu.addItem((item) => {
      item.setTitle("Merge selected cells vertically").setIcon("rows-3").setDisabled(!verticalSelection).onClick(() => {
        if (runMergeCommand(this.app, "vertical", range, verticalSelection)) {
          this.scheduleLivePreviewRefresh(0);
        }
      });
    });
    menu.addItem((item) => {
      item.setTitle("Unmerge selected cells").setIcon("split-square-horizontal").onClick(() => {
        if (runUnmergeCommand(this.app, range, unmergeSelection)) {
          this.scheduleLivePreviewRefresh(0);
        }
      });
    });
  }
  runActiveUnmergeCommand(checking) {
    const active = this.activeMergeSelection;
    if (!active || !active.tableEl.isConnected)
      return false;
    const range = this.tableRanges.get(active.tableEl) || null;
    if (!range)
      return false;
    const selection = expandSelectionForUnmerge(active.tableEl, active.selection);
    if (!checking) {
      if (runUnmergeCommand(this.app, range, selection)) {
        this.scheduleLivePreviewRefresh(0);
      }
    }
    return true;
  }
  /**
   * Locate the raw markdown table block corresponding to a rendered table.
   * Prefer unique content/body/header signatures over brittle
   * "header text appears in a line" matching.
   */
  findTableInSource(fullDoc, tableEl, sourcePath = "") {
    let tableSpecs;
    if (this.specsCache && this.specsCache.documentText === fullDoc) {
      tableSpecs = this.specsCache.specs;
    } else {
      tableSpecs = extractMarkdownTableSpecs(fullDoc);
      this.specsCache = { documentText: fullDoc, specs: tableSpecs };
    }
    const sourceLine = this.getSourceLineForTable(tableEl, sourcePath);
    if (sourceLine !== null && Number.isInteger(sourceLine)) {
      const sourceLineMatch = tableSpecs.find(
        (spec) => sourceLine >= spec.range.startLine && sourceLine <= spec.range.endLine
      );
      if (sourceLineMatch && hasMergeMarkers(sourceLineMatch.text)) {
        return {
          text: sourceLineMatch.text,
          range: sourceLineMatch.range,
          tableOrdinal: sourceLineMatch.tableOrdinal
        };
      }
    }
    const matched = matchMarkdownTableSpecForElement(tableSpecs, tableEl, sourceLine);
    return matched ? { text: matched.text, range: matched.range, tableOrdinal: matched.tableOrdinal } : null;
  }
  setupResizer(tableEl) {
    makeTableResizable(this, tableEl, {
      onResizeStart: () => {
        this.resizingTables.add(tableEl);
        if (this.refreshTimer !== null) {
          window.clearTimeout(this.refreshTimer);
          this.refreshTimer = null;
        }
      },
      onResizeEnd: (widths) => {
        this.resizingTables.delete(tableEl);
        const currentTableId = getTableIds(tableEl);
        if (this.writeWidthsToMarkdown(tableEl, widths)) {
          this.syncWidthsAcrossOpenViews(tableEl, currentTableId, widths);
          return;
        }
        if (this.pendingWidthsSave !== null)
          window.clearTimeout(this.pendingWidthsSave);
        this.pendingWidthsSave = window.setTimeout(() => {
          this.pendingWidthsSave = null;
          saveWidths(this, currentTableId, widths);
        }, 200);
        this.syncWidthsAcrossOpenViews(tableEl, currentTableId, widths);
      }
    });
  }
  syncWidthsAcrossOpenViews(sourceTable, fallbackSourceTableIds, widths) {
    var _a, _b;
    const sourcePath = sourceTable.getAttribute("data-source-path") || ((_b = (_a = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView)) == null ? void 0 : _a.file) == null ? void 0 : _b.path) || "";
    if (!sourcePath)
      return;
    const sourceTableIds = this.ensureTableMetadata(sourceTable, sourcePath);
    const matchIds = sourceTableIds.length ? sourceTableIds : fallbackSourceTableIds;
    for (const tableEl of this.getOpenMarkdownTables(sourcePath)) {
      if (tableEl === sourceTable || tableEl.hasAttribute("data-resizing"))
        continue;
      const tableIds = this.ensureTableMetadata(tableEl, sourcePath);
      if (!this.haveSharedTableId(matchIds, tableIds))
        continue;
      ensureColgroup(tableEl);
      applySavedWidths(tableEl, widths);
    }
  }
  getOpenMarkdownTables(sourcePath) {
    var _a, _b, _c;
    const leaves = ((_b = (_a = this.app.workspace).getLeavesOfType) == null ? void 0 : _b.call(_a, "markdown")) || [];
    const tables = [];
    for (const leaf of leaves) {
      const view = leaf.view;
      if (((_c = view == null ? void 0 : view.file) == null ? void 0 : _c.path) !== sourcePath || !view.contentEl)
        continue;
      tables.push(
        ...Array.from(
          view.contentEl.querySelectorAll("table")
        ).filter((table) => table instanceof HTMLTableElement)
      );
    }
    return tables;
  }
  ensureTableMetadata(tableEl, sourcePath) {
    let tableIds = getTableIds(tableEl);
    const hasStableId = tableIds.some((id) => !id.startsWith("table-fallback-"));
    if (hasStableId)
      return tableIds;
    const match = this.resolveTableSource(tableEl, { sourcePath });
    if (match) {
      this.applyTableMatchMetadata(tableEl, match);
      this.tableRanges.set(tableEl, match.range);
      tableIds = getTableIds(tableEl);
    }
    return tableIds;
  }
  haveSharedTableId(left, right) {
    const rightIds = new Set(right);
    return left.some((id) => rightIds.has(id));
  }
  applyInitialWidths(tableEl, tableId, tableText) {
    const savedWidths = loadWidths(this, tableId);
    if (savedWidths) {
      applySavedWidths(tableEl, savedWidths);
      return;
    }
    if (this.settings.widthPersistence === "markdown" && tableText) {
      const specs = extractMarkdownTableSpecs(tableText);
      const spec = specs[0];
      if (spec == null ? void 0 : spec.columns.length) {
        applySavedWidths(
          tableEl,
          spec.columns.map((column) => column.dashCount * this.settings.pixelsPerDash)
        );
        return;
      }
    }
  }
  writeWidthsToMarkdown(tableEl, widths) {
    if (this.settings.widthPersistence !== "markdown")
      return false;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    const editor = view == null ? void 0 : view.editor;
    const range = this.tableRanges.get(tableEl);
    if (!editor || !range)
      return false;
    const separatorLineIndex = range.startLine + 1;
    const currentLine = editor.getLine(separatorLineIndex);
    const nextLine = buildSeparatorLineForWidths(
      currentLine,
      widths,
      this.settings.pixelsPerDash
    );
    if (!nextLine || nextLine === currentLine)
      return false;
    editor.replaceRange(
      nextLine,
      { line: separatorLineIndex, ch: 0 },
      { line: separatorLineIndex, ch: currentLine.length }
    );
    editor.setCursor({ line: separatorLineIndex, ch: 0 });
    return true;
  }
  scheduleLivePreviewRefresh(delay = 80) {
    if (this.refreshTimer !== null) {
      window.clearTimeout(this.refreshTimer);
    }
    this.refreshTimer = window.setTimeout(() => {
      this.refreshTimer = null;
      this.refreshLivePreviewTables();
    }, delay);
  }
  refreshLivePreviewTables() {
    var _a;
    if (!this.settings.nativeProcessing)
      return;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!(view == null ? void 0 : view.contentEl))
      return;
    const sourcePath = ((_a = view.file) == null ? void 0 : _a.path) || "";
    const tables = Array.from(
      view.contentEl.querySelectorAll("table:not(.sheet-extend-parsed)")
    ).filter((table) => table instanceof HTMLTableElement);
    for (const tableEl of tables) {
      if (tableEl.hasAttribute("data-resizing") || this.resizingTables.has(tableEl)) {
        continue;
      }
      this.processTable(tableEl, { sourcePath });
    }
  }
  observeWorkspaceTables() {
    this.observer = new MutationObserver((mutations) => {
      if (mutations.some(
        (mutation) => Array.from(mutation.addedNodes).some(
          (node) => node instanceof HTMLElement && (node.matches("table") || !!node.querySelector("table"))
        )
      )) {
        this.scheduleLivePreviewRefresh();
      }
    });
    this.observer.observe(document.body, { childList: true, subtree: true });
    this.register(() => {
      var _a;
      return (_a = this.observer) == null ? void 0 : _a.disconnect();
    });
  }
  onunload() {
    var _a;
    document.body.classList.remove("sheet-extend-resizing");
    if (this.refreshTimer !== null) {
      window.clearTimeout(this.refreshTimer);
      this.refreshTimer = null;
    }
    (_a = this.observer) == null ? void 0 : _a.disconnect();
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data == null ? void 0 : data.settings);
    this.widthStore = (data == null ? void 0 : data.columnWidths) || {};
  }
  async saveSettings() {
    await this.saveData({
      version: DATA_VERSION,
      settings: this.settings,
      columnWidths: this.widthStore
    });
  }
};
